### PR TITLE
Stripe keys validation and error handling

### LINKED ISSUE #325: Validation of stripe keys
Do basic validation of Stripe keys in the UI and backend before saving them.  They should all have predictable prefixes.

- `pk_test_` - test publishable key
- `sk_test_` - test secret key
- `pk_live_` - production publishable key
- `sk_live_` - production secret key

### LINKED ISSUE #326: Handle stripe auth failure better
Seen in prod on a key auth failure. This should probably be handled cleaner and dump less unnecessary data into the logs.

    [ERROR] dshop.routes.stripe: Failed to verify stripe credentials { Error: Invalid API Key provided: [censored]
        at IncomingMessage.res.once (/app/node_modules/stripe/lib/StripeResource.js:184:21)
        at Object.onceWrapper (events.js:286:20)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:466:23)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
      type: 'StripeAuthenticationError',
      raw:
       { message: 'Invalid API Key provided: [censored]',
         type: 'invalid_request_error',
         headers:
          { server: 'nginx',
            date: 'Wed, 29 Jul 2020 17:53:40 GMT',
            'content-type': 'application/json',
            'content-length': '109',
            connection: 'keep-alive',
            'access-control-allow-credentials': 'true',
            'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
            'access-control-allow-origin': '*',
            'access-control-expose-headers':
             'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
            'access-control-max-age': '300',
            'cache-control': 'no-cache, no-store',
            'www-authenticate': 'Bearer realm="Stripe"',
            'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
         statusCode: 401,
         requestId: undefined },
      rawType: 'invalid_request_error',
      code: undefined,
      doc_url: undefined,
      param: undefined,
      detail: undefined,
      headers:
       { server: 'nginx',
         date: 'Wed, 29 Jul 2020 17:53:40 GMT',
         'content-type': 'application/json',
         'content-length': '109',
         connection: 'keep-alive',
         'access-control-allow-credentials': 'true',
         'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
         'access-control-allow-origin': '*',
         'access-control-expose-headers':
          'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
         'access-control-max-age': '300',
         'cache-control': 'no-cache, no-store',
         'www-authenticate': 'Bearer realm="Stripe"',
         'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
      requestId: undefined,
      statusCode: 401,
      charge: undefined,
      decline_code: undefined,
      payment_intent: undefined,
      payment_method: undefined,
      setup_intent: undefined,
      source: undefined }

Rel: #325

### PR DESCRIPTION
**Pull request by mikeshultz**
Closes #325 
Closes #326

### CODE REVIEW

File: backend/routes/stripe.js [hunk 1]
```diff
@@ -194,18 +199,20 @@ module.exports = function (router) {
...
 
-      valid = true
-    } catch (err) {
-      log.error('Failed to verify stripe credentials', err)
-      valid = false
+        valid = true
+      } catch (err) {
+        log.error('Failed to verify stripe credentials')
+        log.debug(err)
+        valid = false
```
Comment (franckc) [inline backend/routes/stripe.js:214]: nit: unnecessary since valid was initialized to false on line 201

File: backend/routes/stripe.js [hunk 2]
```diff
@@ -194,18 +199,20 @@ module.exports = function (router) {
 
   router.post('/stripe/check-creds', authShop, async (req, res) => {
     let valid = false
+    const { stripeKey, stripeBackend } = req.body
 
-    try {
-      const { stripeBackend } = req.body
-
-      const stripe = Stripe(stripeBackend)
+    if (validatePublishableKey(stripeKey) && validateSecretKey(stripeBackend)) {
```
Comment (shahthepro) [inline backend/routes/stripe.js:204]: Nit: Perhaps we could add a check to make sure that both are either live or test keys and not mixed. But, don't think it's a problem

Comment (mikeshultz) [reply backend/routes/stripe.js:204]: Good idea.  Gonna do a little refactor to include this check.  Thanks
